export const ClientEvents = {
  MESSAGE_SEND:           'message:send',
  MESSAGE_EDIT:           'message:edit',
  MESSAGE_DELETE:         'message:delete',
  TYPING_START:           'typing:start',
  TYPING_STOP:            'typing:stop',
  PRESENCE_UPDATE:        'presence:update',
  VOICE_JOIN:             'voice:join',
  VOICE_LEAVE:            'voice:leave',
  VOICE_MUTE:             'voice:mute',
  VOICE_DEAFEN:           'voice:deafen',
  VOICE_PRODUCE:          'voice:produce',
  VOICE_CONSUME:          'voice:consume',
  VOICE_RESUME_CONSUMER:  'voice:resume-consumer',
  VOICE_CONNECT_TRANSPORT: 'voice:connect-transport',
  STREAM_START:           'stream:start',
  STREAM_STOP:            'stream:stop',
  SOUNDBOARD_PLAY:        'soundboard:play',
  REACTION_ADD:           'reaction:add',
  REACTION_REMOVE:        'reaction:remove',
  CHANNEL_READ_ACK:       'channel:read-ack',
} as const;

export const ServerEvents = {
  MESSAGE_NEW:            'message:new',
  MESSAGE_UPDATED:        'message:updated',
  MESSAGE_DELETED:        'message:deleted',
  TYPING_UPDATE:          'typing:update',
  PRESENCE_CHANGED:       'presence:changed',
  VOICE_USER_JOINED:      'voice:user-joined',
  VOICE_USER_LEFT:        'voice:user-left',
  VOICE_STATE_UPDATE:     'voice:state-update',
  VOICE_TRANSPORT_CREATED: 'voice:transport-created',
  VOICE_PRODUCED:         'voice:produced',
  VOICE_NEW_PRODUCER:     'voice:new-producer',
  VOICE_PRODUCER_CLOSED:  'voice:producer-closed',
  VOICE_CONSUMED:         'voice:consumed',
  STREAM_STARTED:         'stream:started',
  STREAM_STOPPED:         'stream:stopped',
  SOUNDBOARD_PLAYING:     'soundboard:playing',
  REACTION_ADDED:         'reaction:added',
  REACTION_REMOVED:       'reaction:removed',
  NOTIFICATION_NEW:       'notification:new',
  CHANNEL_CREATED:        'channel:created',
  CHANNEL_UPDATED:        'channel:updated',
  CHANNEL_DELETED:        'channel:deleted',
  USER_UPDATED:           'user:updated',
  ERROR:                  'error',
} as const;

export type ClientEventType = (typeof ClientEvents)[keyof typeof ClientEvents];
export type ServerEventType = (typeof ServerEvents)[keyof typeof ServerEvents];
